-- Catalogos oficiales para carga masiva DFSK
-- Enfoque recomendado: SQL-first
-- 1) Estas consultas son la fuente oficial de catálogos.
-- 2) El Excel solo debe consumir estos resultados.
-- 3) Si cambia un catálogo en base de datos, se actualiza aquí y no en una hoja manual.
-- 4) CATEGORIAF debe depender de GRUPOF usando la consulta correspondiente.
-- MARCAS
SELECT CODIGO,
    DESCRIPCION AS MARCA
FROM CODIGOS
WHERE TIPO = 'M'
ORDER BY DESCRIPCION;
-- GRUPO GENERAL (GRUPOG)
SELECT CASE
        WHEN LTRIM(RTRIM(CODIGO)) <> ''
        AND LTRIM(RTRIM(CODIGO)) NOT LIKE '%[^0-9]%' THEN CAST(LTRIM(RTRIM(CODIGO)) AS INT)
        ELSE NULL
    END AS GRUPOG,
    DESCRIPCION AS NOMBRE_GRUPOG
FROM CODIGOS
WHERE TIPO = 'G'
ORDER BY CASE
        WHEN LTRIM(RTRIM(CODIGO)) <> ''
        AND LTRIM(RTRIM(CODIGO)) NOT LIKE '%[^0-9]%' THEN CAST(LTRIM(RTRIM(CODIGO)) AS INT)
        ELSE NULL
    END,
    DESCRIPCION;
-- CLASIFICACION
SELECT 'GRUPO 1' AS CLASIFICACION
UNION ALL
SELECT 'GRUPO 2'
UNION ALL
SELECT 'GRUPO 3';
-- GRUPO FICHA (GRUPOF)
SELECT G.IDGRUPO AS IDGRUPOF,
    G.GRUPO AS GRUPOF
FROM GRUPOSREPUESTO G
WHERE G.GRUPO IS NOT NULL
ORDER BY G.IDGRUPO,
    G.GRUPO;
-- CATEGORIAS DE FICHA COMPLETAS
SELECT G.IDGRUPO AS IDGRUPOF,
    G.GRUPO AS GRUPOF,
    CR.IDCATEGORIA,
    CR.CATEGORIA AS CATEGORIAF
FROM GRUPOSREPUESTO G
    LEFT JOIN CATEGORIAREPUESTO CR ON CR.IDGRUPO = G.IDGRUPO
WHERE G.GRUPO IS NOT NULL
    AND (
        CR.ESTADO = 1
        OR CR.IDCATEGORIA IS NULL
    )
ORDER BY G.IDGRUPO,
    CR.IDCATEGORIA;
-- CATEGORIAS DE FICHA POR GRUPOF SELECCIONADO
DECLARE @IDGRUPOF INT = 7;
SELECT G.IDGRUPO AS IDGRUPOF,
    G.GRUPO AS GRUPOF,
    CR.IDCATEGORIA,
    CR.CATEGORIA AS CATEGORIAF
FROM GRUPOSREPUESTO G
    LEFT JOIN CATEGORIAREPUESTO CR ON CR.IDGRUPO = G.IDGRUPO
WHERE G.IDGRUPO = @IDGRUPOF
    AND (
        CR.ESTADO = 1
        OR CR.IDCATEGORIA IS NULL
    )
ORDER BY CR.IDCATEGORIA;
-- MODELOS USADOS EN ARTICULOS
SELECT DISTINCT MODELO AS MODELOF
FROM ARTICULOS
WHERE MODELO IS NOT NULL
    AND LTRIM(RTRIM(MODELO)) <> ''
ORDER BY MODELO;
-- TRANSMISION DISPONIBLE
SELECT DISTINCT TRANSMISION AS TRANSMISIONF
FROM ARTICULOS
WHERE TRANSMISION IS NOT NULL
ORDER BY TRANSMISION;
-- PUERTAS DISPONIBLES
SELECT DISTINCT PUERTAS AS PUERTASF
FROM ARTICULOS
WHERE PUERTAS IS NOT NULL
ORDER BY PUERTAS;
-- UBICACION DISPONIBLE
SELECT DISTINCT UBICACION AS UBICACIONF
FROM ARTICULOS
WHERE UBICACION IS NOT NULL
    AND LTRIM(RTRIM(UBICACION)) <> ''
ORDER BY UBICACION;
-- ULTIMO CODIGO SERIE 80000
WITH ARTICULOS_LIMPIOS AS (
    SELECT LTRIM(RTRIM(ARTICULO)) AS ARTICULO_TXT
    FROM ARTICULOS
),
ARTICULOS_NUMERICOS AS (
    SELECT CAST(ARTICULO_TXT AS INT) AS ARTICULO_INT
    FROM ARTICULOS_LIMPIOS
    WHERE ARTICULO_TXT <> ''
        AND ARTICULO_TXT NOT LIKE '%[^0-9]%'
)
SELECT MAX(ARTICULO_INT) AS ULTIMO_80000
FROM ARTICULOS_NUMERICOS
WHERE ARTICULO_INT BETWEEN 80000 AND 89999;
-- ULTIMO CODIGO SERIE 90000
WITH ARTICULOS_LIMPIOS AS (
    SELECT LTRIM(RTRIM(ARTICULO)) AS ARTICULO_TXT
    FROM ARTICULOS
),
ARTICULOS_NUMERICOS AS (
    SELECT CAST(ARTICULO_TXT AS INT) AS ARTICULO_INT
    FROM ARTICULOS_LIMPIOS
    WHERE ARTICULO_TXT <> ''
        AND ARTICULO_TXT NOT LIKE '%[^0-9]%'
)
SELECT MAX(ARTICULO_INT) AS ULTIMO_90000
FROM ARTICULOS_NUMERICOS
WHERE ARTICULO_INT BETWEEN 90000 AND 99999;
-- RESUMEN DE CAPACIDAD POR RANGO (USADOS / DISPONIBLES / RESTANTES)
WITH ARTICULOS_LIMPIOS AS (
    SELECT LTRIM(RTRIM(ARTICULO)) AS ARTICULO_TXT
    FROM ARTICULOS
),
ARTICULOS_NUMERICOS AS (
    SELECT CAST(ARTICULO_TXT AS INT) AS ARTICULO_INT
    FROM ARTICULOS_LIMPIOS
    WHERE ARTICULO_TXT <> ''
        AND ARTICULO_TXT NOT LIKE '%[^0-9]%'
),
RANGOS AS (
    SELECT 80000 AS DESDE,
        89999 AS HASTA,
        'SERIE 80000' AS SERIE
    UNION ALL
    SELECT 90000,
        99999,
        'SERIE 90000'
),
USADOS AS (
    SELECT R.SERIE,
        R.DESDE,
        R.HASTA,
        COUNT(DISTINCT A.ARTICULO_INT) AS CODIGOS_USADOS,
        MAX(A.ARTICULO_INT) AS ULTIMO_CODIGO
    FROM RANGOS R
        LEFT JOIN ARTICULOS_NUMERICOS A ON A.ARTICULO_INT BETWEEN R.DESDE AND R.HASTA
    GROUP BY R.SERIE,
        R.DESDE,
        R.HASTA
)
SELECT SERIE,
    DESDE,
    HASTA,
    (HASTA - DESDE + 1) AS CAPACIDAD_TOTAL,
    CODIGOS_USADOS,
    ((HASTA - DESDE + 1) - CODIGOS_USADOS) AS CODIGOS_RESTANTES,
    ULTIMO_CODIGO,
    CASE
        WHEN ULTIMO_CODIGO IS NULL THEN DESDE
        WHEN ULTIMO_CODIGO < HASTA THEN ULTIMO_CODIGO + 1
        ELSE NULL
    END AS SIGUIENTE_SUGERIDO
FROM USADOS
ORDER BY DESDE;
-- CODIGOS FALTANTES EN UNA SERIE (PARA CONTROL)
DECLARE @SERIE_DESDE INT = 80000;
DECLARE @SERIE_HASTA INT = 89999;
;
WITH NUMEROS AS (
    SELECT @SERIE_DESDE AS CODIGO
    UNION ALL
    SELECT CODIGO + 1
    FROM NUMEROS
    WHERE CODIGO < @SERIE_HASTA
),
SERIE AS (
    SELECT CAST(CODIGO AS VARCHAR(20)) AS CODIGO_SERIE
    FROM NUMEROS
),
ARTICULOS_SERIE AS (
    SELECT LTRIM(RTRIM(ARTICULO)) AS CODIGO_CREADO,
        DESCRIPCION,
        MODELO,
        MARCA
    FROM ARTICULOS
    WHERE LTRIM(RTRIM(ARTICULO)) <> ''
        AND LEN(LTRIM(RTRIM(ARTICULO))) = LEN(CAST(@SERIE_DESDE AS VARCHAR(20)))
        AND LTRIM(RTRIM(ARTICULO)) LIKE LEFT(CAST(@SERIE_DESDE AS VARCHAR(20)), 1) + REPLICATE(
            '[0-9]',
            LEN(CAST(@SERIE_DESDE AS VARCHAR(20))) - 1
        )
)
SELECT S.CODIGO_SERIE AS CODIGO,
    CASE
        WHEN A.CODIGO_CREADO IS NULL THEN 'FALTANTE'
        ELSE 'CREADO'
    END AS ESTADO_CODIGO,
    A.DESCRIPCION,
    A.MODELO,
    A.MARCA
FROM SERIE S
    LEFT JOIN ARTICULOS_SERIE A ON A.CODIGO_CREADO = S.CODIGO_SERIE
ORDER BY S.CODIGO_SERIE OPTION (MAXRECURSION 0);
-- UNIDADES OFICIALES
SELECT TOP (1000) CODIGO,
    DESCRIPCION,
    VALOR
FROM DFSK.DBO.CODIGOUNIDADES
ORDER BY DESCRIPCION;
-- CATEGORIAS DE REPUESTO (CATALOGO COMPLETO)
SELECT TOP (1000) IDCATEGORIA,
    IDGRUPO,
    CATEGORIA,
    ESTADO
FROM DFSK.DBO.CATEGORIAREPUESTO
ORDER BY IDGRUPO,
    IDCATEGORIA;
-- CODIGOS DE VALOR (TIPO I)
SELECT CODIGO,
    DESCRIPCION,
    VALOR
FROM CODIGOSVALOR
WHERE TIPO = 'I'
ORDER BY CASE
        WHEN LTRIM(RTRIM(CODIGO)) <> ''
        AND LTRIM(RTRIM(CODIGO)) NOT LIKE '%[^0-9]%' THEN CAST(LTRIM(RTRIM(CODIGO)) AS INT)
        ELSE NULL
    END,
    CODIGO,
    DESCRIPCION;
-- CLASIFICACION IMB (TIPO 1)
SELECT CODIGO,
    DESCRIPCION
FROM CODIGOS
WHERE TIPO = '1'
ORDER BY CASE
        WHEN LTRIM(RTRIM(CODIGO)) <> ''
        AND LTRIM(RTRIM(CODIGO)) NOT LIKE '%[^0-9]%' THEN CAST(LTRIM(RTRIM(CODIGO)) AS INT)
        ELSE NULL
    END,
    CODIGO,
    DESCRIPCION;
-- PUERTAS (TIPO V)
SELECT CODIGO,
    DESCRIPCION
FROM CODIGOS
WHERE TIPO = 'V'
ORDER BY CASE
        WHEN LTRIM(RTRIM(CODIGO)) <> ''
        AND LTRIM(RTRIM(CODIGO)) NOT LIKE '%[^0-9]%' THEN CAST(LTRIM(RTRIM(CODIGO)) AS INT)
        ELSE NULL
    END,
    CODIGO,
    DESCRIPCION;
-- TRANSMISION (TIPO U)
SELECT CODIGO,
    DESCRIPCION
FROM CODIGOS
WHERE TIPO = 'U'
ORDER BY CASE
        WHEN LTRIM(RTRIM(CODIGO)) <> ''
        AND LTRIM(RTRIM(CODIGO)) NOT LIKE '%[^0-9]%' THEN CAST(LTRIM(RTRIM(CODIGO)) AS INT)
        ELSE NULL
    END,
    CODIGO,
    DESCRIPCION;
-- MODELOS DFSK
SELECT TOP (1000) IDMODELO,
    DESCRIPCION,
    MODELO,
    ANO,
    MARCA,
    ESTADO
FROM DFSK.DBO.MODELOS
ORDER BY IDMODELO;