/*
  Script: update_descripciones.sql
  Acción: actualizar la columna DESCRIPCION en DFSK.DBO.MODELOS según el MODELO.
  Usa COLLATE DATABASE_DEFAULT para evitar conflictos de intercalación.
  Recomendación: ejecutar primero en `prueba_dfsk`.
*/
SET NOCOUNT ON;

BEGIN TRY
    BEGIN TRANSACTION;

    DECLARE @results TABLE (modelo NVARCHAR(200), descripcion NVARCHAR(500), affected INT);

    -- Mapas de actualización
    UPDATE DFSK.DBO.MODELOS
    SET DESCRIPCION = 'DFSK - C31 (1.5L)'
    WHERE ISNULL(MODELO,'') COLLATE DATABASE_DEFAULT = 'C31' COLLATE DATABASE_DEFAULT;
    INSERT INTO @results VALUES('C31','DFSK - C31 (1.5L)', @@ROWCOUNT);

    UPDATE DFSK.DBO.MODELOS
    SET DESCRIPCION = 'DFSK - C32 (1.5L)'
    WHERE ISNULL(MODELO,'') COLLATE DATABASE_DEFAULT = 'C32' COLLATE DATABASE_DEFAULT;
    INSERT INTO @results VALUES('C32','DFSK - C32 (1.5L)', @@ROWCOUNT);

    UPDATE DFSK.DBO.MODELOS
    SET DESCRIPCION = 'DFSK - C35 (1.5L)'
    WHERE ISNULL(MODELO,'') COLLATE DATABASE_DEFAULT = 'C35' COLLATE DATABASE_DEFAULT;
    INSERT INTO @results VALUES('C35','DFSK - C35 (1.5L)', @@ROWCOUNT);

    UPDATE DFSK.DBO.MODELOS
    SET DESCRIPCION = 'DFSK - C37 (1.5L)'
    WHERE ISNULL(MODELO,'') COLLATE DATABASE_DEFAULT = 'C37' COLLATE DATABASE_DEFAULT;
    INSERT INTO @results VALUES('C37','DFSK - C37 (1.5L)', @@ROWCOUNT);

    UPDATE DFSK.DBO.MODELOS
    SET DESCRIPCION = 'DFSK - D1 (2.4L)'
    WHERE ISNULL(MODELO,'') COLLATE DATABASE_DEFAULT = 'D1' COLLATE DATABASE_DEFAULT;
    INSERT INTO @results VALUES('D1','DFSK - D1 (2.4L)', @@ROWCOUNT);

    UPDATE DFSK.DBO.MODELOS
    SET DESCRIPCION = 'DFSK - D51 (1.5L)'
    WHERE ISNULL(MODELO,'') COLLATE DATABASE_DEFAULT = 'D51' COLLATE DATABASE_DEFAULT;
    INSERT INTO @results VALUES('D51','DFSK - D51 (1.5L)', @@ROWCOUNT);

    UPDATE DFSK.DBO.MODELOS
    SET DESCRIPCION = 'DFSK - D71 (2.0L)'
    WHERE ISNULL(MODELO,'') COLLATE DATABASE_DEFAULT = 'D71' COLLATE DATABASE_DEFAULT;
    INSERT INTO @results VALUES('D71','DFSK - D71 (2.0L)', @@ROWCOUNT);

    UPDATE DFSK.DBO.MODELOS
    SET DESCRIPCION = 'DFSK - D72 (2.0L)'
    WHERE ISNULL(MODELO,'') COLLATE DATABASE_DEFAULT = 'D72' COLLATE DATABASE_DEFAULT;
    INSERT INTO @results VALUES('D72','DFSK - D72 (2.0L)', @@ROWCOUNT);

    UPDATE DFSK.DBO.MODELOS
    SET DESCRIPCION = 'DFSK - E5'
    WHERE ISNULL(MODELO,'') COLLATE DATABASE_DEFAULT = 'E5' COLLATE DATABASE_DEFAULT;
    INSERT INTO @results VALUES('E5','DFSK - E5', @@ROWCOUNT);

    UPDATE DFSK.DBO.MODELOS
    SET DESCRIPCION = 'DFSK - GLORY 330 (1.5L)'
    WHERE ISNULL(MODELO,'') COLLATE DATABASE_DEFAULT = 'GLORY330' COLLATE DATABASE_DEFAULT;
    INSERT INTO @results VALUES('GLORY330','DFSK - GLORY 330 (1.5L)', @@ROWCOUNT);

    UPDATE DFSK.DBO.MODELOS
    SET DESCRIPCION = 'DFSK - GLORY 500 (1.5L)'
    WHERE ISNULL(MODELO,'') COLLATE DATABASE_DEFAULT = 'GLORY500' COLLATE DATABASE_DEFAULT;
    INSERT INTO @results VALUES('GLORY500','DFSK - GLORY 500 (1.5L)', @@ROWCOUNT);

    UPDATE DFSK.DBO.MODELOS
    SET DESCRIPCION = 'DFSK - GLORY 500 TURBO (1.5L TURBO)'
    WHERE ISNULL(MODELO,'') COLLATE DATABASE_DEFAULT = 'GLORY500T' COLLATE DATABASE_DEFAULT;
    INSERT INTO @results VALUES('GLORY500T','DFSK - GLORY 500 TURBO (1.5L TURBO)', @@ROWCOUNT);

    UPDATE DFSK.DBO.MODELOS
    SET DESCRIPCION = 'DFSK - GLORY 560 (1.8L)'
    WHERE ISNULL(MODELO,'') COLLATE DATABASE_DEFAULT = 'GLORY560' COLLATE DATABASE_DEFAULT;
    INSERT INTO @results VALUES('GLORY560','DFSK - GLORY 560 (1.8L)', @@ROWCOUNT);

    UPDATE DFSK.DBO.MODELOS
    SET DESCRIPCION = 'DFSK - GLORY 580 (1.8L)'
    WHERE ISNULL(MODELO,'') COLLATE DATABASE_DEFAULT = 'GLORY580' COLLATE DATABASE_DEFAULT;
    INSERT INTO @results VALUES('GLORY580','DFSK - GLORY 580 (1.8L)', @@ROWCOUNT);

    UPDATE DFSK.DBO.MODELOS
    SET DESCRIPCION = 'DFSK - GLORY 600 (1.5L TURBO)'
    WHERE ISNULL(MODELO,'') COLLATE DATABASE_DEFAULT = 'GLORY600' COLLATE DATABASE_DEFAULT;
    INSERT INTO @results VALUES('GLORY600','DFSK - GLORY 600 (1.5L TURBO)', @@ROWCOUNT);

    UPDATE DFSK.DBO.MODELOS
    SET DESCRIPCION = 'DFSK - IX5 (1.5L TURBO)'
    WHERE ISNULL(MODELO,'') COLLATE DATABASE_DEFAULT = 'IX5' COLLATE DATABASE_DEFAULT;
    INSERT INTO @results VALUES('IX5','DFSK - IX5 (1.5L TURBO)', @@ROWCOUNT);

    -- K01S variants
    UPDATE DFSK.DBO.MODELOS
    SET DESCRIPCION = 'DFSK - K01S (1.1L)'
    WHERE ISNULL(MODELO,'') COLLATE DATABASE_DEFAULT = 'K01S_11' COLLATE DATABASE_DEFAULT;
    INSERT INTO @results VALUES('K01S_11','DFSK - K01S (1.1L)', @@ROWCOUNT);

    UPDATE DFSK.DBO.MODELOS
    SET DESCRIPCION = 'DFSK - K01S (1.2L)'
    WHERE ISNULL(MODELO,'') COLLATE DATABASE_DEFAULT = 'K01S_12' COLLATE DATABASE_DEFAULT;
    INSERT INTO @results VALUES('K01S_12','DFSK - K01S (1.2L)', @@ROWCOUNT);

    UPDATE DFSK.DBO.MODELOS
    SET DESCRIPCION = 'DFSK - K02S (1.1L)'
    WHERE ISNULL(MODELO,'') COLLATE DATABASE_DEFAULT = 'K02S' COLLATE DATABASE_DEFAULT;
    INSERT INTO @results VALUES('K02S','DFSK - K02S (1.1L)', @@ROWCOUNT);

    UPDATE DFSK.DBO.MODELOS
    SET DESCRIPCION = 'DFSK - K05S (1.1L)'
    WHERE ISNULL(MODELO,'') COLLATE DATABASE_DEFAULT = 'K05S' COLLATE DATABASE_DEFAULT;
    INSERT INTO @results VALUES('K05S','DFSK - K05S (1.1L)', @@ROWCOUNT);

    UPDATE DFSK.DBO.MODELOS
    SET DESCRIPCION = 'DFSK - K07S (1.1L)'
    WHERE ISNULL(MODELO,'') COLLATE DATABASE_DEFAULT = 'K07S' COLLATE DATABASE_DEFAULT;
    INSERT INTO @results VALUES('K07S','DFSK - K07S (1.1L)', @@ROWCOUNT);

    UPDATE DFSK.DBO.MODELOS
    SET DESCRIPCION = 'GAC - EMPOW'
    WHERE ISNULL(MODELO,'') COLLATE DATABASE_DEFAULT = 'GAC_EMPOW' COLLATE DATABASE_DEFAULT;
    INSERT INTO @results VALUES('GAC_EMPOW','GAC - EMPOW', @@ROWCOUNT);

    UPDATE DFSK.DBO.MODELOS
    SET DESCRIPCION = 'GAC - EMPOW (R-STYLE)'
    WHERE ISNULL(MODELO,'') COLLATE DATABASE_DEFAULT = 'GAC_EMPOW_R' COLLATE DATABASE_DEFAULT;
    INSERT INTO @results VALUES('GAC_EMPOW_R','GAC - EMPOW (R-STYLE)', @@ROWCOUNT);

    UPDATE DFSK.DBO.MODELOS
    SET DESCRIPCION = 'GAC - EMZOOM'
    WHERE ISNULL(MODELO,'') COLLATE DATABASE_DEFAULT = 'GAC_EMZOOM' COLLATE DATABASE_DEFAULT;
    INSERT INTO @results VALUES('GAC_EMZOOM','GAC - EMZOOM', @@ROWCOUNT);

    UPDATE DFSK.DBO.MODELOS
    SET DESCRIPCION = 'GAC - EMZOOM (R-STYLE)'
    WHERE ISNULL(MODELO,'') COLLATE DATABASE_DEFAULT = 'GAC_EMZOOM_R' COLLATE DATABASE_DEFAULT;
    INSERT INTO @results VALUES('GAC_EMZOOM_R','GAC - EMZOOM (R-STYLE)', @@ROWCOUNT);

    UPDATE DFSK.DBO.MODELOS
    SET DESCRIPCION = 'GAC - GS8'
    WHERE ISNULL(MODELO,'') COLLATE DATABASE_DEFAULT = 'GAC_GS8' COLLATE DATABASE_DEFAULT;
    INSERT INTO @results VALUES('GAC_GS8','GAC - GS8', @@ROWCOUNT);

    UPDATE DFSK.DBO.MODELOS
    SET DESCRIPCION = 'GAC - S7'
    WHERE ISNULL(MODELO,'') COLLATE DATABASE_DEFAULT = 'GAC_S7' COLLATE DATABASE_DEFAULT;
    INSERT INTO @results VALUES('GAC_S7','GAC - S7', @@ROWCOUNT);

    UPDATE DFSK.DBO.MODELOS
    SET DESCRIPCION = 'GAC - SMILODON PRO'
    WHERE ISNULL(MODELO,'') COLLATE DATABASE_DEFAULT = 'GAC_SMILODON_PRO' COLLATE DATABASE_DEFAULT;
    INSERT INTO @results VALUES('GAC_SMILODON_PRO','GAC - SMILODON PRO', @@ROWCOUNT);

    UPDATE DFSK.DBO.MODELOS
    SET DESCRIPCION = 'GAC - SMILODON SE'
    WHERE ISNULL(MODELO,'') COLLATE DATABASE_DEFAULT = 'GAC_SMILODON_SE' COLLATE DATABASE_DEFAULT;
    INSERT INTO @results VALUES('GAC_SMILODON_SE','GAC - SMILODON SE', @@ROWCOUNT);

    UPDATE DFSK.DBO.MODELOS
    SET DESCRIPCION = 'SHINERAY - X30'
    WHERE ISNULL(MODELO,'') COLLATE DATABASE_DEFAULT = 'X30' COLLATE DATABASE_DEFAULT;
    INSERT INTO @results VALUES('X30','SHINERAY - X30', @@ROWCOUNT);

    UPDATE DFSK.DBO.MODELOS
    SET DESCRIPCION = 'SHINERAY - X30LS'
    WHERE ISNULL(MODELO,'') COLLATE DATABASE_DEFAULT = 'X30LS' COLLATE DATABASE_DEFAULT;
    INSERT INTO @results VALUES('X30LS','SHINERAY - X30LS', @@ROWCOUNT);

    -- Adicional: asegurar G560/GLORY560 si existe
    UPDATE DFSK.DBO.MODELOS
    SET DESCRIPCION = 'DFSK - GLORY 560 (1.8L)'
    WHERE ISNULL(MODELO,'') COLLATE DATABASE_DEFAULT IN (
      'G560' COLLATE DATABASE_DEFAULT,
      'GLORY560' COLLATE DATABASE_DEFAULT
    );
    INSERT INTO @results VALUES('G560/GLORY560','DFSK - GLORY 560 (1.8L)', @@ROWCOUNT);

    -- Resultado
    SELECT modelo, descripcion, affected FROM @results ORDER BY modelo;

    COMMIT TRANSACTION;

    PRINT 'Actualización de descripciones completada.';

END TRY
BEGIN CATCH
    DECLARE @ErrNum INT = ERROR_NUMBER();
    DECLARE @ErrMsg NVARCHAR(4000) = ERROR_MESSAGE();
    ROLLBACK TRANSACTION;
    RAISERROR('Error %d: %s',16,1,@ErrNum,@ErrMsg);
END CATCH
